### ISSUE TITLE
无法显示中文问题

### ISSUE THREAD

**Issue by txthinking** [brook-community/script#3]
1. 购买一个 aws lightsail ubuntu 20
2. 直接在web页面点击ssh连接
3. 进入后 sudo su 切换到root
4. 粘贴 bash <(curl -sL https://brook-community.github.io/script/install.sh)

提示的中文显示乱码

建议如果可以帮助小白处理下会更好

![image](https://user-images.githubusercontent.com/1241807/97775797-65b3d880-1b9e-11eb-9960-e52d965432a5.png)

**Comment by McDull-GitHub** [comment]
我加入了簡體中文，並且加入了 `export LC_ALL=zh_CN.UTF-8` 不知道對於中文的顯示是否有幫助，請麻煩你再試一次。

**Comment by txthinking** [comment]
用Terminal ssh进入没有问题. 使用aws的web ssh就有问题. 应该是aws web ssh 的问题. 
https://hostloc.com/thread-619933-1-1.html
